In [1]:
import torch

In [2]:
x = torch.arange(12)

In [3]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

torch.Size([12])

In [5]:
x.numel()

12

In [6]:
x.reshape(3, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
y = torch.zeros(2, 3, 4)

In [8]:
y

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
torch.ones(2, 3, 4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [10]:
torch.randn(2, 3, 4)

tensor([[[-0.5025,  0.0359, -0.7163, -0.6758],
         [-0.8908, -1.3829,  1.0296, -0.0662],
         [ 0.5513, -0.5980, -1.9170,  2.8632]],

        [[-1.3116,  0.3236,  1.8299,  0.9586],
         [ 0.3979, -0.4339, -1.2558,  0.8292],
         [-1.5189, -0.4874,  1.0528,  1.6829]]])

In [11]:
zz = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [12]:
type(zz)

torch.Tensor

In [13]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [14]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [17]:
X = torch.randn((2, 3), dtype=torch.float32)
Y = torch.randn((2, 3), dtype=torch.float16)

In [19]:
torch.cat((X, Y), dim=0)

tensor([[-0.1011,  0.8689, -1.6031],
        [-0.0686,  0.1707,  0.7582],
        [-1.6465, -0.6470, -1.7168],
        [ 1.6807,  0.6782, -2.1660]])

In [20]:
torch.cat((X, Y), dim=1)

tensor([[-0.1011,  0.8689, -1.6031, -1.6465, -0.6470, -1.7168],
        [-0.0686,  0.1707,  0.7582,  1.6807,  0.6782, -2.1660]])

In [21]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [22]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 2197976772336
id(Z): 2197976772336


In [23]:
before = id(X)
X += Y
id(X) == before

True

In [24]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [26]:
a = torch.tensor([3.4])
a, a.item(), float(a), int(a)

(tensor([3.4000]), 3.4000000953674316, 3.4000000953674316, 3)